### ISSUE TITLE
Linux 下使用报错 "ValueError: not enough image data"

### ISSUE THREAD

**Issue by L0snight** [ninthDevilHAUNSTER/ArknightsAutoHelper#134]
系统: Arch Linux
模拟器: genymotion
模拟器安卓信息: Android 10+ 1280 x 720 分辨率
tesseract:
&nbsp;&nbsp;&nbsp;&nbsp;version: 4.1.1
&nbsp;&nbsp;&nbsp;&nbsp;list-langs: chi_sim/chi_tra/eng/osd
复现步骤: python3 akhelper.py quick 2，第一次战斗结束后出现这样的报错。有时第一次战斗之前也会出此报错。
预期现象：可以正常模拟。
报错信息：
```
Traceback (most recent call last):
  File "akhelper.py", line 6, in <module>
    sys.exit(Arknights.shell_next.main(sys.argv))
  File "/home/l0snight/Workspace/ArknightsAutoHelper/Arknights/shell_next.py", line 227, in main
    return targetcmd(argv[1:])
  File "/home/l0snight/Workspace/ArknightsAutoHelper/Arknights/shell_next.py", line 84, in quick
    helper.module_battle_slim(
  File "/home/l0snight/Workspace/ArknightsAutoHelper/Arknights/helper.py", line 230, in module_battle_slim
    self.operation_once_statemachine(c_id, )
  File "/home/l0snight/Workspace/ArknightsAutoHelper/Arknights/helper.py", line 442, in operation_once_statemachine
    smobj.state(smobj)
  File "/home/l0snight/Workspace/ArknightsAutoHelper/Arknights/helper.py", line 358, in on_operation
    screenshot = self.adb.screenshot()
  File "/home/l0snight/Workspace/ArknightsAutoHelper/connector/ADBConnector.py", line 186, in screenshot
    img = _screencap_to_image(rawcap)
  File "/home/l0snight/Workspace/ArknightsAutoHelper/connector/ADBConnector.py", line 23, in _screencap_to_image
    return Image.frombytes('RGBA', (w, h), pixels)
  File "/home/l0snight/.local/lib/python3.8/site-packages/PIL/Image.py", line 2542, in frombytes
    im.frombytes(data, decoder_name, args)
  File "/home/l0snight/.local/lib/python3.8/site-packages/PIL/Image.py", line 829, in frombytes
    raise ValueError("not enough image data")
ValueError: not enough image data
```

**Comment by pingplug** [comment]
行号看起来不太对，是不是用的不是最新版本？
用master分支的最新版试试？

**Comment by L0snight** [comment]
> 行号看起来不太对，是不是用的不是最新版本？
> 用master分支的最新版试试？

当时测试的时候是dev分支的最新的commit, 然后刚才有测试了。会出现反复设置代理指挥一段时间后，报出同样的错误。
log如下:

> python akhelper.py quick 1

 ```
Ξ 确认设备名称：192.168.56.102:5555
 Ξ 正在使用模拟器优化模式
 Ξ 战斗-选择None...启动
 Ξ 当前门票 117, 关卡消耗 30
 Ξ 设置代理指挥
 Ξ 当前门票 117, 关卡消耗 30
 Ξ 设置代理指挥
 Ξ 当前门票 117, 关卡消耗 30
 Ξ 设置代理指挥
 Ξ 当前门票 117, 关卡消耗 30
 Ξ 设置代理指挥
 Ξ 当前门票 117, 关卡消耗 30
 Ξ 设置代理指挥
 Ξ 当前门票 117, 关卡消耗 30
 Ξ 设置代理指挥
 Ξ 当前门票 117, 关卡消耗 30
 Ξ 设置代理指挥
 Ξ 当前门票 117, 关卡消耗 30
 Ξ 设置代理指挥
 Ξ 当前门票 117, 关卡消耗 30
 Ξ 设置代理指挥
 Ξ 当前门票 117, 关卡消耗 30
 Ξ 设置代理指挥
 Ξ 当前门票 117, 关卡消耗 30
 Ξ 设置代理指挥
 Ξ 当前门票 117, 关卡消耗 30
 Ξ 设置代理指挥
 Ξ 当前门票 117, 关卡消耗 30
 Ξ 设置代理指挥
 Ξ 当前门票 117, 关卡消耗 30
 Ξ 设置代理指挥
 Ξ 当前门票 117, 关卡消耗 30
 Ξ 设置代理指挥
 Ξ 当前门票 117, 关卡消耗 30
 Ξ 设置代理指挥
 Ξ 当前门票 117, 关卡消耗 30
 Ξ 设置代理指挥
Traceback (most recent call last):
  File "akhelper.py", line 6, in <module>
    sys.exit(Arknights.shell_next.main(sys.argv))
  File "/home/l0snight/Workspace/ArknightsAutoHelper/Arknights/shell_next.py", line 227, in main
    return targetcmd(argv[1:])
  File "/home/l0snight/Workspace/ArknightsAutoHelper/Arknights/shell_next.py", line 84, in quick
    helper.module_battle_slim(
  File "/home/l0snight/Workspace/ArknightsAutoHelper/Arknights/helper.py", line 218, in module_battle_slim
    self.operation_once_statemachine(c_id, )
  File "/home/l0snight/Workspace/ArknightsAutoHelper/Arknights/helper.py", line 431, in operation_once_statemachine
    smobj.state(smobj)
  File "/home/l0snight/Workspace/ArknightsAutoHelper/Arknights/helper.py", line 257, in on_prepare
    screenshot = self.adb.screenshot()
  File "/home/l0snight/Workspace/ArknightsAutoHelper/connector/ADBConnector.py", line 224, in screenshot
    img = _screencap_to_image(rawcap)
  File "/home/l0snight/Workspace/ArknightsAutoHelper/connector/ADBConnector.py", line 24, in _screencap_to_image
    return Image.frombytes('RGBA', (w, h), pixels)
  File "/home/l0snight/.local/lib/python3.8/site-packages/PIL/Image.py", line 2542, in frombytes
    im.frombytes(data, decoder_name, args)
  File "/home/l0snight/.local/lib/python3.8/site-packages/PIL/Image.py", line 829, in frombytes
    raise ValueError("not enough image data")
ValueError: not enough image data
```

**Comment by dantmnf** [comment]
这里有两个问题。

第一个无限循环的问题建议检查 log/imgreco.before_operation.html，附参考
![image](https://user-images.githubusercontent.com/2252500/90271134-e7447600-de8d-11ea-9851-b62a4b4cf5a0.png)

第二个问题（not enough image data）是 adb 返回的数据不完整/错误导致的，目前属于玄学问题（

**Comment by L0snight** [comment]
我看了一下Log，里面的图是和参考的图是类似的，就只是代理指挥的图一直在选中和取消选定来回变。关于第二个问题，既然是玄学问题，那就有时间的话自己会尝试解决一下，谢谢。
![Screenshot_20200815_172520](https://user-images.githubusercontent.com/19932520/90309597-9596fc80-df1c-11ea-873e-c78580b5e1fe.png)

**Comment by L0snight** [comment]
在上面这个commit下，目前来看一切都正常了。谢谢。
