### ISSUE TITLE
求助 先是ADB启动失败 然后又是这个错误  最新的二进制包

### ISSUE THREAD

**Issue by Noomnus** [ninthDevilHAUNSTER/ArknightsAutoHelper#152]
Traceback (most recent call last):
  File "Arknights\shell_next.py", line 217, in interactive
  File "Arknights\shell_next.py", line 159, in collect
  File "Arknights\shell_next.py", line 37, in _create_helper
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "D:\a\ArknightsAutoHelper\ArknightsAutoHelper\venv64\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
  File "Arknights\helper.py", line 12, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "D:\a\ArknightsAutoHelper\ArknightsAutoHelper\venv64\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
  File "config\__init__.py", line 13, in <module>
AttributeError: module 'ruamel.yaml' has no attribute 'YAML'

**Comment by Noomnus** [comment]
换成源码版也报错
Traceback (most recent call last):
  File "akhelper.py", line 6, in <module>
    sys.exit(Arknights.shell_next.main(sys.argv))
  File "D:\360安全浏览器下载\ArknightsAutoHelper-master\Arknights\shell_next.py", line 276, in main
    return targetcmd(argv[1:])
  File "D:\360安全浏览器下载\ArknightsAutoHelper-master\Arknights\shell_next.py", line 159, in collect
    helper = _create_helper()
  File "D:\360安全浏览器下载\ArknightsAutoHelper-master\Arknights\shell_next.py", line 37, in _create_helper
    from Arknights.helper import ArknightsHelper
  File "D:\360安全浏览器下载\ArknightsAutoHelper-master\Arknights\helper.py", line 9, in <module>
    import coloredlogs
ModuleNotFoundError: No module named 'coloredlogs'

**Comment by Noomnus** [comment]
Ξ 尝试启动 adb server
Traceback (most recent call last):
  File "Arknights\shell_next.py", line 220, in interactive
  File "Arknights\shell_next.py", line 121, in quick
  File "Arknights\shell_next.py", line 38, in _create_helper
  File "Arknights\helper.py", line 56, in __init__
  File "connector\ADBConnector.py", line 99, in ensure_adb_alive
OSError: can't start adb server

**Comment by Noomnus** [comment]
MUMU模拟器 以前能用现状不知道哪里不对劲
