### ISSUE TITLE
主战斗模块报错

### ISSUE THREAD

**Issue by windskyxb** [ninthDevilHAUNSTER/ArknightsAutoHelper#153]
akhelper> auto 1-7 1
 Ξ 确认设备名称：127.0.0.1:7555
 Ξ 装载模块...
 Ξ 战斗模块...启动
 Ξ 开始 1-7
 Ξ 正在返回主页
Traceback (most recent call last):
  File "Arknights\shell_next.py", line 220, in interactive
  File "Arknights\shell_next.py", line 149, in auto
  File "Arknights\helper.py", line 551, in main_handler
  File "Arknights\helper.py", line 532, in module_battle
  File "Arknights\helper.py", line 682, in goto_stage
  File "Arknights\helper.py", line 525, in back_to_main
RuntimeError: 未知画面

**Comment by windskyxb** [comment]
akhelper> c
 Ξ 确认设备名称：127.0.0.1:7555
 Ξ 领取每日任务
 Ξ 正在返回主页
Traceback (most recent call last):
  File "Arknights\shell_next.py", line 220, in interactive
  File "Arknights\shell_next.py", line 164, in collect
  File "Arknights\helper.py", line 573, in clear_daily_task
  File "Arknights\helper.py", line 525, in back_to_main
RuntimeError: 未知画面

**Comment by windskyxb** [comment]
2020-12-05 10:17:46,571 ! <module> @ __init__.py:202 ! DEBUG ! ArknightsAutoHelper version master+d755b11-ci
2020-12-05 10:17:46,674 ! check_adb_alive @ ADBConnector.py:83 ! DEBUG ! ADB server version 32
2020-12-05 10:17:46,675 ! __adb_device_name_detector @ ADBConnector.py:232 ! INFO ! 没有已连接设备，尝试连接 127.0.0.1:7555
2020-12-05 10:17:46,675 ! disconnect @ ADBClientSession.py:61 ! DEBUG ! adb disconnect 127.0.0.1:7555: No such device 127.0.0.1:7555
2020-12-05 10:17:46,677 ! connect @ ADBClientSession.py:55 ! DEBUG ! adb connect 127.0.0.1:7555: connected to 127.0.0.1:7555
2020-12-05 10:18:34,607 ! check_adb_alive @ ADBConnector.py:83 ! DEBUG ! ADB server version 32
2020-12-05 10:18:34,611 ! __adb_device_name_detector @ ADBConnector.py:269 ! INFO ! 确认设备名称：127.0.0.1:7555
2020-12-05 10:18:34,645 ! __init__ @ ADBConnector.py:211 ! DEBUG ! device identifier: android-b114f136a6c17001
2020-12-05 10:18:34,647 ! load_device_config @ ADBConnector.py:380 ! DEBUG ! using device-specific config in database
2020-12-05 10:18:34,900 ! __init__ @ helper.py:86 ! DEBUG ! 成功初始化模块
2020-12-05 10:18:34,902 ! main_handler @ helper.py:541 ! INFO ! 装载模块...
2020-12-05 10:18:34,902 ! main_handler @ helper.py:542 ! INFO ! 战斗模块...启动
2020-12-05 10:18:34,903 ! main_handler @ helper.py:550 ! INFO ! 开始 1-7
2020-12-05 10:18:34,903 ! module_battle @ helper.py:531 ! DEBUG ! helper.module_battle
2020-12-05 10:18:34,903 ! back_to_main @ helper.py:472 ! INFO ! 正在返回主页
2020-12-05 10:18:49,113 ! check_adb_alive @ ADBConnector.py:83 ! DEBUG ! ADB server version 32
2020-12-05 10:18:49,114 ! __adb_device_name_detector @ ADBConnector.py:269 ! INFO ! 确认设备名称：127.0.0.1:7555
2020-12-05 10:18:49,126 ! __init__ @ ADBConnector.py:211 ! DEBUG ! device identifier: android-b114f136a6c17001
2020-12-05 10:18:49,126 ! load_device_config @ ADBConnector.py:380 ! DEBUG ! using device-specific config in database
2020-12-05 10:18:49,300 ! __init__ @ helper.py:86 ! DEBUG ! 成功初始化模块
2020-12-05 10:18:49,305 ! clear_daily_task @ helper.py:571 ! DEBUG ! helper.clear_daily_task
2020-12-05 10:18:49,306 ! clear_daily_task @ helper.py:572 ! INFO ! 领取每日任务
2020-12-05 10:18:49,312 ! back_to_main @ helper.py:472 ! INFO ! 正在返回主页

**Comment by windskyxb** [comment]
Ξ 载入企鹅数据资源...                                                                                                  Ξ 载入企鹅数据资源出错                                                                                                Traceback (most recent call last):                                                                                        File "penguin_stats\reporter.py", line 93, in initialize                                                                File "penguin_client\api\item_api.py", line 54, in get_all_items_using_get1                                             File "penguin_client\api\item_api.py", line 107, in get_all_items_using_get1_with_http_info                             File "penguin_client\api_client.py", line 325, in call_api                                                              File "penguin_client\api_client.py", line 157, in __call_api                                                            File "penguin_client\api_client.py", line 347, in request                                                               File "penguin_client\rest.py", line 234, in GET                                                                         File "penguin_client\rest.py", line 207, in request                                                                     File "urllib3\request.py", line 74, in request                                                                          File "urllib3\request.py", line 96, in request_encode_url                                                               File "urllib3\poolmanager.py", line 375, in urlopen                                                                     File "urllib3\connectionpool.py", line 719, in urlopen                                                                  File "urllib3\response.py", line 601, in from_httplib                                                                   File "urllib3\response.py", line 260, in __init__                                                                       File "urllib3\response.py", line 515, in read                                                                           File "http\client.py", line 465, in read                                                                                File "http\client.py", line 572, in _readall_chunked                                                                    File "http\client.py", line 555, in _get_chunk_left                                                                     File "http\client.py", line 515, in _read_next_chunk_size                                                               File "socket.py", line 704, in readinto                                                                                 File "ssl.py", line 1241, in recv_into                                                                                  File "ssl.py", line 1099, in read                                                                                     KeyboardInterrupt                                                                                                        Ξ 未上报掉落截图已保存到 C:\Program Files (x86)\akhelper\screenshot\未上报掉落-1607243081.png
