### ISSUE TITLE
GUI问题

### ISSUE THREAD

**Issue by LittleNightmare** [ninthDevilHAUNSTER/ArknightsAutoHelper#18]
`C:\Users\dell\AppData\Local\Programs\Python\Python37-32\python.exe E:/GitHub/ArknightsAutoHelper/GUI_start.py
E:\GitHub\ArknightsAutoHelper\GUI\Frames\Index.py:235: wxPyDeprecationWarning: Call to deprecated item. Use :meth:`AddTool` instead.
  wx.ITEM_NORMAL, wx.EmptyString, wx.EmptyString, None)
Traceback (most recent call last):
  File "E:/GitHub/ArknightsAutoHelper/GUI_start.py", line 2, in <module>
    start_app()
  File "E:\GitHub\ArknightsAutoHelper\GUI\app.py", line 110, in start_app
    ArknightsAutoHelperGUI().MainLoop()
  File "E:\GitHub\ArknightsAutoHelper\GUI\app.py", line 26, in __init__
    self.backend_buffer_push()
  File "E:\GitHub\ArknightsAutoHelper\GUI\app.py", line 51, in backend_buffer_push
    buffer = self.ark.shell_color.get_buffer()
AttributeError: 'NoneType' object has no attribute 'shell_color'

Process finished with exit code 1
`
~~我是真的不知道怎么改了~~

### 已解决

**Comment by LittleNightmare** [comment]
GUI打开了，暂时gui问题应该没了，就是测试的功能我没读，试了俩下没看出来干嘛，旁边的理智在开始前没有办法更改，改了后就变回去
