### ISSUE TITLE
运行 connect 报错 ADBClientSession.py  line 12  in _check_okay     raise RuntimeError

### ISSUE THREAD

**Issue by RikkaBlue** [ninthDevilHAUNSTER/ArknightsAutoHelper#188]
https://github.com/ninthDevilHAUNSTER/ArknightsAutoHelper/blob/0ce17f27724a4e2d2eb9caab8960fa4fe4d3dc14/connector/ADBClientSession.py#L9

错误似乎是这一行的报错。

```python
akhelper> connect
[INFO] 确认设备名称：emulator-5554
Traceback (most recent call last):
  File "D:\ark\ArknightsAutoHelper\Arknights\shell_next.py", line 272, in interactive
    errorlevel = cmd(argv)
  File "D:\ark\ArknightsAutoHelper\Arknights\shell_next.py", line 126, in connect
    _connect_adb(connector_args)
  File "D:\ark\ArknightsAutoHelper\Arknights\shell_next.py", line 136, in _connect_adb
    device = ADBConnector()
  File "D:\ark\ArknightsAutoHelper\connector\ADBConnector.py", line 216, in __init__
    self.load_device_config()
  File "D:\ark\ArknightsAutoHelper\connector\ADBConnector.py", line 420, in load_device_config
    self._probe_device_config(device_record)
  File "D:\ark\ArknightsAutoHelper\connector\ADBConnector.py", line 484, in _probe_device_config
    loopbacks = self._detect_loopbacks()
  File "D:\ark\ArknightsAutoHelper\connector\ADBConnector.py", line 338, in _detect_loopbacks
    modules = self.device_session_factory().exec('grep -o vboxguest /proc/modules')
  File "D:\ark\ArknightsAutoHelper\connector\ADBClientSession.py", line 88, in exec
    sock = self.exec_stream(cmd)
  File "D:\ark\ArknightsAutoHelper\connector\ADBClientSession.py", line 81, in exec_stream
    self.service('exec:' + cmd)
  File "D:\ark\ArknightsAutoHelper\connector\ADBClientSession.py", line 40, in service
    _check_okay(self.sock)
  File "D:\ark\ArknightsAutoHelper\connector\ADBClientSession.py", line 12, in _check_okay
    raise RuntimeError(_read_hexlen(sock))
RuntimeError: b'closed'
```
---
### 模拟器是 Bluestacks v4.280.0.1022
```bash
(venv) ➜  ArknightsAutoHelper git:(master) ✗ adb devices
List of devices attached
emulator-5554   device
```
安装目录是默认的  `C:\Program Files\BlueStacks`

### 配置文件：
```yaml
device:
  # ADB server 的端口。部分模拟器为避免冲突可能会将 ADB server 开在其他端口，
  # 此时可以更改此设置以利用模拟器自带的 ADB server。
  # adb_server: 127.0.0.1:5037

  # 需要启动 adb server 时，使用的 adb 命令
  # 为空时则尝试: 1. PATH 中的 adb；
  #               2. ADB/{sys.platform}/adb;
  #               3. 查找 Android SDK（ANDROID_SDK_ROOT 和默认安装目录）
  adb_binary:
  # 以下为部分模拟器提供的 adb 程序，不一定正确，仅供参考
  # adb_binary: D:\leidian\LDPlayer\adb.exe             # 雷电模拟器
    adb_binary: C:\Program Files\BlueStacks\HD-Adb.exe  # BlueStacks
  # adb_binary: C:\Program Files (x86)\MuMu\emulator\nemu\vmonitor\bin\adb_server.exe  # MuMu模拟器

  # 始终选择指定设备进行操作（指定 adb devices 中列出的名称）
  # adb_always_use_device:

  # 无设备连接时进行的操作
  # 如果某个操作报告成功，则不再执行后续定义的操作
  adb_no_device_fixups:
  - run: probe_bluestacks_hyperv  # 自动探测并连接 BlueStacks Hyper-V 的 ADB 端口
  - run: adb_connect  # 连接 ADB TCP/IP 端口
    target:
      - 127.0.0.1:5555  # 大部分模拟器
      - 127.0.0.1:7555  # MuMu模拟器
    try_all: false  # 某个端口连接成功后，是否继续尝试后续定义的端口

  # 使用兼容性较好（但较慢）的截图方式
  compat_screenshot: false

  # 通过 adb 传输模拟器截图数据较慢时，尝试绕过 adbd 传输截图数据
  # 模拟器判断逻辑：1. 设备名称以 "emulator-" 或 "127.0.0.1:" 开头
  #                 2. ro.product.board 包含 goldfish（SDK emulator）或存在 vboxguest 模块
  # 可用选项：never, auto, always
  workaround_slow_emulator_adb: auto

  # 截图缓存：如果两次截图间隔小于上次截图耗时，则直接返回上次的截图
  cache_screenshot: true

  package_name: com.hypergryph.arknights
  # package_name: com.hypergryph.arknights.bilibili
  activity_name: com.u8.sdk.U8UnityContext

ocr:
  # 选择 OCR 引擎，非必要
  # 设置为 auto 则选择下列第一个可用的引擎: tesseract, windows_media_ocr, baidu
  engine: auto

  # 百度 API 设置，使用 baidu OCR 时需要正确填写
  baidu_api:
    # 是否将百度 OCR 标记为可用
    enabled: false
    # 百度 API 鉴权数据
    app_id: STUB
    app_key: STUB
    app_secret: STUB

reporting:
  # 是否将关卡掉落上传到企鹅数据 (penguin-stats.io)
  enabled: false

  # 企鹅数据的用户 ID
  # > 用户 ID 仅用来标记您的上传身份。在不同设备上使用此 ID 登录，可让掉落数据集中于一个账号下，方便管理上传以及查看个人掉落数据。
  # 如果为 null 或空，则在下一次上传时创建并更新到文件中
  penguin_stats_uid:

behavior:
  # 理智不足时自动使用理智回复道具
  # 免责声明：可能存在识别错误导致碎石，开发者对此不负任何责任
  refill_ap_with_item: false

  # 理智不足时自动碎石
  # 如需使用，请将大写字母改为小写
  REFILL_AP_WITH_ORIGINIUM: false

  # 代理指挥出现失误的处理
  mistaken_delegation:
    # 是否以 2 星结算关卡
    settle: false
    # 结算/放弃后，是否跳过失误关卡
    skip: true

  # 启用 ocr 前往关卡
  use_ocr_goto_stage: false

plan:
  # 刷图计划执行完毕后，用剩余理智刷这个关卡
#  idle_stage: '1-7'

  # 刷 idle_stage 理智不足时自动使用理智回复道具
  # 免责声明：可能存在识别错误导致碎石，开发者对此不负任何责任
  refill_ap_with_item: true

  # 刷 idle_stage 理智不足时自动碎石
  # 如需使用，请将大写字母改为小写
  REFILL_AP_WITH_ORIGINIUM: false
```

**Comment by RikkaBlue** [comment]
已解决，需要在 Bluestacks 中手动打开 adb 功能
