### ISSUE TITLE
收获信赖失败

### ISSUE THREAD

**Issue by yikakia** [ninthDevilHAUNSTER/ArknightsAutoHelper#201]
报错信息

```log
[!] 正在唤起 ArknightsAutoHelper
 Ξ 领取信赖
 Ξ 正在返回主页
Traceback (most recent call last):
  File "ArknightsShell.py", line 4, in <module>
    shell.run_shell()
  File "D:\Codes\ArknightsAutoHelper\Arknights\ArknightsShell.py", line 33, in run_shell
    self.handler()
  File "D:\Codes\ArknightsAutoHelper\Arknights\ArknightsShell.py", line 100, in handler
    Ark.get_credit()
  File "D:\Codes\ArknightsAutoHelper\Arknights\helper.py", line 818, in get_credit
    self.back_to_main()
  File "D:\Codes\ArknightsAutoHelper\Arknights\helper.py", line 501, in back_to_main
    screenshot = self.adb.screenshot()
AttributeError: 'NoneType' object has no attribute 'screenshot'
```

首先，感谢各位开发者开发的工具，真的非常方便，帮了我很多🙏。

今天更新到 `9e5ec140c40960186a22323e1fbd6c9960832495` 后遇到了这个问题，要收获信赖的时候失败了。我用的是整合工具箱。

看报错是 `adb` 没初始化么？

**Comment by yikakia** [comment]
https://github.com/ninthDevilHAUNSTER/ArknightsAutoHelper/blob/9e5ec140c40960186a22323e1fbd6c9960832495/Arknights/ArknightsShell.py#L83

看了下代码，应该是整合工具箱对于收获信赖，是通过调用 `ArknightsShell` 而调用 `helper.py` 中的 `ArknightsHelper` 模块。这里就有个问题是现在的 `ArknightsHelper` 的初始化要求提供 `adb_host`、`device_connector` 中的一者才能初始化 `adb` 而在 `ArknightsShell` 中调用时并没有传入对应的参数。

现在有种解决方法是
# 方法一
https://github.com/ninthDevilHAUNSTER/ArknightsAutoHelper/blob/9e5ec140c40960186a22323e1fbd6c9960832495/Arknights/helper.py#L815

```diff
    def get_credit(self):
        logger.debug("helper.get_credit")
        logger.info("领取信赖")
+        if self.adb is None :
+            self.connect_device(ADBConnector.auto_connect())
```

这样可以只影响这个模块，我看了下整合工具箱现在只有收获信赖用的是这个模块，其他的都迁移到 `shell_next` 中了。所以这么改影响最小。

但是我发现好像 `shell_next` 也是基于 `ArknightsHelper` 来实现的，这么改可能过于耦合了。所以应该可能这么改更好
# 方法二
https://github.com/ninthDevilHAUNSTER/ArknightsAutoHelper/blob/9e5ec140c40960186a22323e1fbd6c9960832495/Arknights/ArknightsShell.py#L83
```diff
    def handler(self):
+        from connector.ADBConnector import ADBConnector
        if self.options.module_battle_slim | self.options.module_battle | self.options.clear_daily | self.options.get_credit | self.options.get_building:
-           Ark = ArknightsHelper()
+           Ark = ArknightsHelper(device_connector = ADBConnector.auto_connect())
```
也可以这么改
# 方法三
https://github.com/ninthDevilHAUNSTER/ArknightsAutoHelper/blob/9e5ec140c40960186a22323e1fbd6c9960832495/Arknights/ArknightsShell.py#L83
```diff
    def handler(self):
+        from connector.ADBConnector import ensure_adb_alive
        if self.options.module_battle_slim | self.options.module_battle | self.options.clear_daily | self.options.get_credit | self.options.get_building:
            Ark = ArknightsHelper()
+           ensure_adb_alive()
```

当然了，如果为了其他人基于 `ArknightsHelper` 模块开发的时候不受影响的话，也可以这么改
# 方法四
https://github.com/ninthDevilHAUNSTER/ArknightsAutoHelper/blob/9e5ec140c40960186a22323e1fbd6c9960832495/Arknights/helper.py#L60
```diff
class ArknightsHelper(object):
    def __init__(self, adb_host=None, device_connector=None, frontend=None):  # 当前绑定到的设备
        self.adb = None
        if adb_host is not None or device_connector is not None:
            self.connect_device(device_connector, adb_serial=adb_host)
+        if self.adb is None :
+            self.connect_device(ADBConnector.auto_connect())
```
这样相当于是做了最后一层保险，所有对 `ArknightsHelper` 的调用都会被 `auto_connect()` 兜底。

个人比较倾向于采用方法三，因为 `shell_next` 中也是这么实现的。而方法四也可以加上，作为最后的兜底措施。避免以后出现 `shell_next_next` 的时候可能还会因为修改了参数而导致 `shell_next` 中的旧模块失效。
