### ISSUE TITLE
提示上报失败 刷的1-7

### ISSUE THREAD

**Issue by UVJkiNTQ** [ninthDevilHAUNSTER/ArknightsAutoHelper#234]
`Traceback (most recent call last):
  File "D:\ArknightsAutoHelper\Arknights\helper.py", line 461, in on_end_operation
    drops = imgreco.end_operation.recognize(smobj.prepare_reco['style'], screenshot)
  File "D:\ArknightsAutoHelper\imgreco\end_operation.py", line 205, in recognize
    return recognize_main(im)
  File "D:\ArknightsAutoHelper\imgreco\end_operation.py", line 273, in recognize_main
    raise RuntimeError('possibly incomplete item list')
RuntimeError: possibly incomplete item list

未上报掉落截图已保存到 D:\ArknightsAutoHelper\screenshot\未上报掉落-1626446424.png`

**Comment by UVJkiNTQ** [comment]
是不是多了活动材料的原因？

**Comment by dantmnf** [comment]
大概是 #135

**Comment by UVJkiNTQ** [comment]
看了图，就是了。换超宽屏了。
