### ISSUE TITLE
运行gui报错

### ISSUE THREAD

**Issue by AkariRin** [ninthDevilHAUNSTER/ArknightsAutoHelper#235]
最新版本运行gui的时候出现报错
报错内容如下：
`D:\ArknightsAutoHelper>python akhelper-gui.pyw
http://127.0.0.1:52131/?token=1145141919
Traceback (most recent call last):
  File "C:\Program Files\Python38\lib\site-packages\gevent\threadpool.py", line 167, in __run_task
    thread_result.set(func(*args, **kwargs))
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb5 in position 7: invalid start byte
2021-07-16T15:27:15Z (<ThreadPoolWorker at 0x15c3357e1a0 thread_ident=0x2b0c threadpool-hub=<Hub at 0x15c33466940 thread_ident=0x1750>>, <built-in function gethostbyaddr>) failed with UnicodeDecodeError

Traceback (most recent call last):
  File "src\\gevent\\greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "C:\Program Files\Python38\lib\site-packages\gevent\baseserver.py", line 398, in serve_forever    
    self.start()
  File "C:\Program Files\Python38\lib\site-packages\gevent\baseserver.py", line 336, in start
    self.init_socket()
  File "C:\Program Files\Python38\lib\site-packages\gevent\pywsgi.py", line 1546, in init_socket
    self.update_environ()
  File "C:\Program Files\Python38\lib\site-packages\gevent\pywsgi.py", line 1558, in update_environ      
    name = socket.getfqdn(address[0])
  File "C:\Program Files\Python38\lib\site-packages\gevent\_socketcommon.py", line 304, in getfqdn       
    hostname, aliases, _ = gethostbyaddr(name)
  File "C:\Program Files\Python38\lib\site-packages\gevent\_socketcommon.py", line 276, in gethostbyaddr 
    return get_hub().resolver.gethostbyaddr(ip_address)
  File "C:\Program Files\Python38\lib\site-packages\gevent\resolver\thread.py", line 66, in gethostbyaddr
    return self.pool.apply(_socket.gethostbyaddr, args, kwargs)
  File "C:\Program Files\Python38\lib\site-packages\gevent\pool.py", line 161, in apply
    return self.spawn(func, *args, **kwds).get()
  File "src\\gevent\\event.py", line 329, in gevent._gevent_cevent.AsyncResult.get
  File "src\\gevent\\event.py", line 359, in gevent._gevent_cevent.AsyncResult.get
  File "src\\gevent\\event.py", line 347, in gevent._gevent_cevent.AsyncResult.get
  File "src\\gevent\\event.py", line 327, in gevent._gevent_cevent.AsyncResult._raise_exception
  File "C:\Program Files\Python38\lib\site-packages\gevent\_compat.py", line 65, in reraise
    raise value.with_traceback(tb)
  File "C:\Program Files\Python38\lib\site-packages\gevent\threadpool.py", line 167, in __run_task
    thread_result.set(func(*args, **kwargs))
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb5 in position 7: invalid start byte
2021-07-16T15:27:15Z <Greenlet at 0x15c30e29590: <bound method BaseServer.serve_forever of <WSGIServer at 0x15c3355bf70 fileno=364 address=127.0.0.1:52131>>> failed with UnicodeDecodeError

stopping idle server

D:\ArknightsAutoHelper>`

**Comment by dantmnf** [comment]
> File "C:\Program Files\Python38\lib\site-packages\gevent_socketcommon.py", line 276, in gethostbyaddr
> return get_hub().resolver.gethostbyaddr(ip_address)
> UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb5 in position 7: invalid start byte

计算机名（hostname）是否有非 ASCII 字符？

**Comment by AkariRin** [comment]
问题已解决，感谢
