### ISSUE TITLE
无法在蓝叠模拟器下正常使用

### ISSUE THREAD

**Issue by Tianpeng2333** [ninthDevilHAUNSTER/ArknightsAutoHelper#259]
模拟器版本为 3.1.21.799，引擎版本为 4.260.2.3003，模拟器已开启“允许 adb 连接”选项，并已经通过 `adb connect`  命令成功连接模拟器。
已尝试使用最新版本的二进制包以及源代码。 Adb 也已尝试过使用最新版本以及蓝叠自带的 HD-Adb 程序连接。

报错日志如下：
```plain
Traceback (most recent call last):
  File "Arknights\shell_next.py", line 286, in interactive
  File "Arknights\shell_next.py", line 132, in connect
  File "Arknights\shell_next.py", line 139, in _connect_adb
  File "connector\ADBConnector.py", line 125, in ensure_adb_alive
OSError: can't start adb server
```

**Comment by NineMeowHL** [comment]
试试MeoAssistantArknights，蓝叠的话要读取额外的conf
