### ISSUE TITLE
git pull之后报错

### ISSUE THREAD

**Issue by wky9710** [ninthDevilHAUNSTER/ArknightsAutoHelper#269]
```
akhelper> q
Traceback (most recent call last):
  File "D:\basic_downloads\模拟器MUMU\ArknightsAutoHelper\Arknights\shell_next.py", line 286, in interactive
    errorlevel = cmd(argv)
  File "D:\basic_downloads\模拟器MUMU\ArknightsAutoHelper\Arknights\shell_next.py", line 183, in quick
    helper, context = _create_helper(show_toggle=True)
  File "D:\basic_downloads\模拟器MUMU\ArknightsAutoHelper\Arknights\shell_next.py", line 47, in _create_helper
    from Arknights.helper import ArknightsHelper
  File "D:\basic_downloads\模拟器MUMU\ArknightsAutoHelper\Arknights\helper.py", line 16, in <module>
    import imgreco.common
  File "D:\basic_downloads\模拟器MUMU\ArknightsAutoHelper\imgreco\common.py", line 3, in <module>
    from util import cvimage as Image
  File "D:\basic_downloads\模拟器MUMU\ArknightsAutoHelper\util\cvimage.py", line 19, in <module>
    NEAREST = NONE = cv2.INTER_NEAREST_EXACT
AttributeError: module 'cv2.cv2' has no attribute 'INTER_NEAREST_EXACT'
```
回退版本之后正常，不确认是不是我这里的问题。感谢。

**Comment by dantmnf** [comment]
需要更新依赖库版本： `pip install -U -r requirements.txt`

**Comment by wky9710** [comment]
已解决，感谢
