### ISSUE TITLE
在Terminal中激活venv后直接运行py akhelper.py命令报错

### ISSUE THREAD

**Issue by pboymt** [ninthDevilHAUNSTER/ArknightsAutoHelper#274]
报错如下：

```pwsh
(venv) PS E:\git\ArknightsAutoHelper> py akhelper.py quick +r5
Traceback (most recent call last):
  File "E:\git\ArknightsAutoHelper\akhelper.py", line 8, in <module>
    sys.exit(Arknights.shell_next.main(sys.argv))
  File "E:\git\ArknightsAutoHelper\Arknights\shell_next.py", line 345, in main
    return targetcmd(argv[1:])
  File "E:\git\ArknightsAutoHelper\Arknights\shell_next.py", line 183, in quick
    helper, context = _create_helper(show_toggle=True)
  File "E:\git\ArknightsAutoHelper\Arknights\shell_next.py", line 47, in _create_helper
    from Arknights.helper import ArknightsHelper
  File "E:\git\ArknightsAutoHelper\Arknights\helper.py", line 12, in <module>
    import coloredlogs
ModuleNotFoundError: No module named 'coloredlogs'
```

这种问题仅在命令行中激活venv后执行`py akhelper.py`运行时才会出现。

在命令行是否激活venv执行批处理文件运行快速模式、打开GUI均没问题，在图形界面运行批处理业务也无问题。

**Comment by dantmnf** [comment]
建议直接使用 venv 的 python 命令，py launcher 最后调用了哪个 python 不好说。

**Comment by pboymt** [comment]
啊这，还真是python正常，py报错，我已经看不懂了。

py -0命令显示用的venv里面的，但还是有问题，太怪了。
