### ISSUE TITLE
运行脚本时报错：TypeError: 'ABCMeta' object is not subscriptable

### ISSUE THREAD

**Issue by Gitucc** [ninthDevilHAUNSTER/ArknightsAutoHelper#277]
akhelper.py与akhelper-gui.pyw均出现同样问题
环境conda 4.11.0基于Python 3.8.12
**akhelper-gui.pyw**
```
(venv) (base) PS D:\Users\xxx\Documents\ArknightsAutoHelper> python akhelper-gui.pyw
http://127.0.0.1:62757/?token=1145141919
[pywebview] Using WinForms / Chromium
received request {'type': 'web:authorize', 'token': '1145141919'}
client authorized
spawning worker process
starting worker loop
Process Process-2:
Traceback (most recent call last):
  File "D:\Anaconda3\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "D:\Anaconda3\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "D:\Users\xxx\Documents\ArknightsAutoHelper\webgui2\worker_launcher.py", line 6, in worker_process
    from . import worker
  File "D:\Users\xxx\Documents\ArknightsAutoHelper\webgui2\worker.py", line 7, in <module>
    import Arknights.helper
  File "D:\Users\xxx\Documents\ArknightsAutoHelper\Arknights\helper.py", line 10, in <module>
    from automator import BaseAutomator
  File "D:\Users\xxx\Documents\ArknightsAutoHelper\automator\__init__.py", line 3, in <module>
    from .helper import BaseAutomator, AddonBase
  File "D:\Users\xxx\Documents\ArknightsAutoHelper\automator\helper.py", line 15, in <module>
    from .frontend import Frontend, DummyFrontend
  File "D:\Users\xxx\Documents\ArknightsAutoHelper\automator\frontend.py", line 5, in <module>
    class Frontend(ABC):
  File "D:\Users\xxx\Documents\ArknightsAutoHelper\automator\frontend.py", line 29, in Frontend
    def context(self) -> AbstractContextManager[None]:
TypeError: 'ABCMeta' object is not subscriptable
```
**akhelper.py**
```
(venv) (base) PS D:\Users\xxx\Documents\ArknightsAutoHelper> python akhelper.py
Traceback (most recent call last):
  File "akhelper.py", line 7, in <module>
    import Arknights.configure_launcher
  File "D:\Users\xxx\Documents\ArknightsAutoHelper\Arknights\configure_launcher.py", line 1, in <module>
    from .helper import ArknightsHelper
  File "D:\Users\xxx\Documents\ArknightsAutoHelper\Arknights\helper.py", line 10, in <module>
    from automator import BaseAutomator
  File "D:\Users\xxx\Documents\ArknightsAutoHelper\automator\__init__.py", line 3, in <module>
    from .helper import BaseAutomator, AddonBase
  File "D:\Users\xxx\Documents\ArknightsAutoHelper\automator\helper.py", line 15, in <module>
    from .frontend import Frontend, DummyFrontend
  File "D:\Users\xxx\Documents\ArknightsAutoHelper\automator\frontend.py", line 5, in <module>
    class Frontend(ABC):
  File "D:\Users\xxx\Documents\ArknightsAutoHelper\automator\frontend.py", line 29, in Frontend
    def context(self) -> AbstractContextManager[None]:
TypeError: 'ABCMeta' object is not subscriptable
```

**Comment by dantmnf** [comment]
hmm...
3.8 的 AbstractContextManager 没有 __class_getitem__，要用 typing.ContextManager，但是 typing.ContextManager 在 3.9 又 deprecate 了。
