### ISSUE TITLE
1月24日，通过git pull更新到最新，GUI无法使用！表现为点击按钮后没有任何动作，界面卡死。

### ISSUE THREAD

**Issue by xf22cn** [ninthDevilHAUNSTER/ArknightsAutoHelper#297]
尝试解决的办法：pip install -r requirements.txt --index-url https://mirrors.aliyun.com/pypi/simple
重新安装后，故障依然存在，没用……

**Comment by UVJkiNTQ** [comment]
尝试使用工具箱替代，报错如下：


Traceback (most recent call last):
  File "D:\ArknightsAutoHelper\\akhelper.py", line 8, in <module>
    import Arknights.configure_launcher
  File "D:\ArknightsAutoHelper\Arknights\configure_launcher.py", line 1, in <module>
    from .helper import ArknightsHelper
  File "D:\ArknightsAutoHelper\Arknights\helper.py", line 10, in <module>
    from automator import BaseAutomator
  File "D:\ArknightsAutoHelper\automator\__init__.py", line 3, in <module>
    from .helper import BaseAutomator, AddonBase
  File "D:\ArknightsAutoHelper\automator\helper.py", line 15, in <module>
    from .connector.ADBConnector import ADBConnector
  File "D:\ArknightsAutoHelper\automator\connector\ADBConnector.py", line 15, in <module>
    from util import cvimage as Image
  File "D:\ArknightsAutoHelper\util\cvimage.py", line 15, in <module>
    import cv2
  File "D:\ArknightsAutoHelper\venv\lib\site-packages\cv2\__init__.py", line 9, in <module>
    from .cv2 import _registerMatType
ImportError: cannot import name '_registerMatType' from 'cv2.cv2' (D:\ArknightsAutoHelper\venv\lib\site-packages\cv2\cv2.cp38-win_amd64.pyd)

[已退出进程，代码为 1]

**Comment by UVJkiNTQ** [comment]
发现python要求3.9了，换个版本……

**Comment by UVJkiNTQ** [comment]
经测试，直接使用二进制包没问题，请换用python3.9或使用二进制包 @xf22cn 

只有一个提示：HCN API not availiable，不影响运行
