### ISSUE TITLE
[Runtime Error] NoneType object appears in tesseract BaseAPI class

### ISSUE THREAD

**Issue by MrAru** [ninthDevilHAUNSTER/ArknightsAutoHelper#298]
```
>>> python akhelper.py recruit
 Ξ 识别招募标签
 Ξ HCN API not availiable
 Ξ 可选标签：重装干员 先锋干员 远程位 新手 群攻
先锋干员: 凛冬 德克萨斯 苇草 清道夫 红豆 桃金娘 芬 香草 翎羽 夜刀
群攻: 幽灵鲨 陨星 送葬人 布洛卡 远山 白雪 艾丝黛尔 格雷伊 炎熔 空爆 泡普卡
远程位: 白面鸮 蓝毒 白金 陨星 梅尔 赫默 华法琳 普罗旺斯 守林人 初雪 真理 夜魔 格劳克斯 送葬人 灰喉 惊蛰 夜烟 远山 杰西卡 流星 白雪 末药 嘉维尔 调香师 地灵 格雷伊 苏苏洛 红云 清流 梅 安比尔 克洛丝 安德切尔 炎熔 芙蓉 安赛尔 史都华德 梓兰 空爆 巡林者 杜林 12F Lancet-2 正义骑士号
重装干员: 临光 雷蛇 可颂 火神 吽 角峰 蛇屠箱 古米 米格鲁 斑点 黑角
群攻,远程位: 陨星 送葬人 远山 白雪 格雷伊 炎熔 空爆
新手: 夜刀 黑角 巡林者 杜林 12F
先锋干员,新手: 夜刀
新手,远程位: 巡林者 杜林 12F
新手,重装干员: 黑角
Exception ignored in: <function BaseAPI.__del__ at 0x7fd3cfcb92d0>
Traceback (most recent call last):
  File "/home/aru/Temporary/ArknightsAutoHelper/imgreco/ocr/tesseract/tessbaseapi.py", line 125, in __del__
  File "/home/aru/Temporary/ArknightsAutoHelper/imgreco/ocr/tesseract/tessbaseapi.py", line 129, in release
  File "/home/aru/Temporary/ArknightsAutoHelper/imgreco/ocr/tesseract/tessbaseapi.py", line 84, in <lambda>
AttributeError: 'NoneType' object has no attribute 'nullcontext'
```

Version info:
Arknights Auto Helper: latest git commit
Python: 3.10
tesseract: 4.1.1

**Comment by dantmnf** [comment]
Seems like globals of `tessbaseapi` module destroyed before a `BaseAPI` instance.

Need an alternative way to implement object finalizer.
