### ISSUE TITLE
基建更换干员报错：cv2模块不包含xfeatures2d

### ISSUE THREAD

**Issue by pboymt** [ninthDevilHAUNSTER/ArknightsAutoHelper#308]
运行环境：Linux ubuntu 5.13.0-1016-raspi #18-Ubuntu SMP PREEMPT Thu Jan 20 08:53:01 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux

报错内容：

```
akhelper adb:127.0.0.1:5555> riic shift B103 格雷伊
 Ξ 返回上层
 Ξ 满足停止条件，停止导航
 Ξ 进入房间 B103
 Ξ 正在识别基建布局
Traceback (most recent call last):
  File "/home/ubuntu/git/ArknightsAutoHelper/automator/launcher.py", line 172, in command_internal
    errorlevel = cmd(argv)
  File "/home/ubuntu/git/ArknightsAutoHelper/Arknights/addons/riic/__init__.py", line 414, in cli_riic
    self.shift(room, operators)
  File "/home/ubuntu/git/ArknightsAutoHelper/Arknights/addons/riic/__init__.py", line 386, in shift
    self.enter_operator_selection(room)
  File "/home/ubuntu/git/ArknightsAutoHelper/Arknights/addons/riic/__init__.py", line 346, in enter_operator_selection
    self.enter_room(room)
  File "/home/ubuntu/git/ArknightsAutoHelper/Arknights/addons/riic/__init__.py", line 325, in enter_room
    layout = self.recognize_layout()
  File "/home/ubuntu/git/ArknightsAutoHelper/Arknights/addons/riic/__init__.py", line 108, in recognize_layout
    match = imgops.match_feature_orb(resources.load_image_cached('riic/layout.png', 'L'), screenshot.convert('L'), templ_mask=templ_mask, haystack_mask=screen_mask, limited_transform=True)
  File "/home/ubuntu/git/ArknightsAutoHelper/imgreco/imgops.py", line 185, in match_feature_orb
    descriptor = cv.xfeatures2d.BEBLID_create(0.75)
AttributeError: module 'cv2' has no attribute 'xfeatures2d'
```

**Comment by pboymt** [comment]
完全卸载`opencv-contrib-python`后重新安装最新版依赖可以解决，建议把`requirements.txt`里面的版本改一下……
