### ISSUE TITLE
基建更换干员出现RuntimeError('not here')错误

### ISSUE THREAD

**Issue by pboymt** [ninthDevilHAUNSTER/ArknightsAutoHelper#309]
运行环境：Linux ubuntu 5.13.0-1016-raspi #18-Ubuntu SMP PREEMPT Thu Jan 20 08:53:01 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux

运行指令和报错内容：
```
akhelper> riic shift B103 格雷伊
 Ξ 返回上层
 Ξ 满足停止条件，停止导航
 Ξ 进入房间 B103
 Ξ 正在识别基建布局
Traceback (most recent call last):
  File "/home/ubuntu/git/ArknightsAutoHelper/automator/launcher.py", line 172, in command_internal
    errorlevel = cmd(argv)
  File "/home/ubuntu/git/ArknightsAutoHelper/Arknights/addons/riic/__init__.py", line 414, in cli_riic
    self.shift(room, operators)
  File "/home/ubuntu/git/ArknightsAutoHelper/Arknights/addons/riic/__init__.py", line 387, in shift
    self.select_operators(operators)
  File "/home/ubuntu/git/ArknightsAutoHelper/Arknights/addons/riic/__init__.py", line 359, in select_operators
    current_page = self.recognize_operator_select(deselect=deselect, recognize_skill=False)
  File "/home/ubuntu/git/ArknightsAutoHelper/Arknights/addons/riic/__init__.py", line 142, in recognize_operator_select
    raise RuntimeError('not here')
RuntimeError: not here
```

**Comment by dantmnf** [comment]
截图一下当前画面（原始分辨率，PNG 格式）

**Comment by pboymt** [comment]
![cap](https://user-images.githubusercontent.com/10893582/152715031-4e2448c0-4872-4a41-95b6-35a5f540f311.png)

**Comment by dantmnf** [comment]
大意了，发电站没有清除选择按钮（

**Comment by pboymt** [comment]
> 大意了，发电站没有清除选择按钮（

寄，那办公室不也得翻车吗？

**Comment by pboymt** [comment]
好了，的确翻车了：
```
 Ξ 返回上层
 Ξ 满足停止条件，停止导航
 Ξ 进入房间 office
 Ξ 正在识别基建布局
Traceback (most recent call last):
  File "/home/ubuntu/git/ArknightsAutoHelper/akhelper.py", line 11, in <module>
    sys.exit(automator.launcher.main(sys.argv))
  File "/home/ubuntu/git/ArknightsAutoHelper/automator/launcher.py", line 313, in main
    return targetcmd(argv[1:])
  File "/home/ubuntu/git/ArknightsAutoHelper/Arknights/addons/riic/__init__.py", line 414, in cli_riic
    self.shift(room, operators)
  File "/home/ubuntu/git/ArknightsAutoHelper/Arknights/addons/riic/__init__.py", line 387, in shift
    self.select_operators(operators)
  File "/home/ubuntu/git/ArknightsAutoHelper/Arknights/addons/riic/__init__.py", line 359, in select_operators
    current_page = self.recognize_operator_select(deselect=deselect, recognize_skill=False)
  File "/home/ubuntu/git/ArknightsAutoHelper/Arknights/addons/riic/__init__.py", line 142, in recognize_operator_select
    raise RuntimeError('not here')
RuntimeError: not here
```
