### ISSUE TITLE
运行报错 `TypeError: 'type' object is not subscriptable`

### ISSUE THREAD

**Issue by qrqhuang** [ninthDevilHAUNSTER/ArknightsAutoHelper#310]
python版本:  `3.8.6`
code rev:  b9b2eccafecd23cb50cdb4043e0cd16c31134829

```
(venv) F:\src\github\ArknightsAutoHelper>python akhelper-gui.pyw
Traceback (most recent call last):
  File "akhelper-gui.pyw", line 6, in <module>
    import webgui2.server
  File "F:\src\github\ArknightsAutoHelper\webgui2\server.py", line 25, in <module>
    import app
  File "F:\src\github\ArknightsAutoHelper\app\__init__.py", line 15, in <module>
    from . import schema
  File "F:\src\github\ArknightsAutoHelper\app\schema.py", line 1, in <module>
    from .schemadef import *
  File "F:\src\github\ArknightsAutoHelper\app\schemadef.py", line 45, in <module>
    class ListField(Field[list[ElementType]]):
TypeError: 'type' object is not subscriptable
```

**Comment by dantmnf** [comment]
最近加了一堆 type hint，需要 3.9 了。

**Comment by qrqhuang** [comment]
好的 谢谢
