### ISSUE TITLE
结算界面烟火行动活动期间经常报错且凋落物识别出现错误

### ISSUE THREAD

**Issue by RimuruChan** [ninthDevilHAUNSTER/ArknightsAutoHelper#315]
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\ArknightsAutoHelper\Arknights\addons\combat.py", line 314, in on_end_operation
    drops = imgreco.end_operation.recognize(smobj.prepare_reco['style'], screenshot, True)
  File "C:\Users\Administrator\Desktop\ArknightsAutoHelper\imgreco\end_operation.py", line 206, in recognize
    return recognize_main(im, learn_unrecognized_item)
  File "C:\Users\Administrator\Desktop\ArknightsAutoHelper\imgreco\end_operation.py", line 274, in recognize_main
    raise RuntimeError('possibly incomplete item list')
RuntimeError: possibly incomplete item list

**Comment by dantmnf** [comment]
因为列表溢出了，一次截图截不全。

workaround 是把分辨率拉长。
