### ISSUE TITLE
macOS GUI 无法运行

### ISSUE THREAD

**Issue by AndyChen2005121** [ninthDevilHAUNSTER/ArknightsAutoHelper#72]
```
$ python3 GUI_start.py

Traceback (most recent call last):
  File "/Users/andychen/Documents/arkgui/GUI/app.py", line 94, in OnInit
    self.Index = Index(parent=None)
  File "/Users/andychen/Documents/arkgui/GUI/Frames/Index.py", line 294, in __init__
    wx.Font(12, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, False, "等线"))
wx._core.wxAssertionError: C++ assertion "IsAttached()" failed at /Users/robind/projects/buildbots/macosx-vm6/dist-osx-py37/Phoenix/ext/wxWidgets/src/osx/menu_osx.cpp(711) in Refresh(): can't refresh unatteched menubar
OnInit returned false, exiting...
```

**Comment by ninthDevilHAUNSTER** [comment]
啊嘞啊嘞...我没有MAC誒。

是在启动的过程中发现的问题么？我猜测可能是字体的锅。回头还需要有MAC的同学多测试一下。

**Comment by AndyChen2005121** [comment]
@ninthDevilHAUNSTER 从错误信息里我猜可能是字体, 因为你们也许只在Windows下测试过.

要注意"等线"**不是跨平台字体.**

**Comment by AndyChen2005121** [comment]
@ninthDevilHAUNSTER 现在把GUI/Frames/Index.py的293-294行去掉, 可以正常显示, 但又出现了这样的问题: 
```
一些文字框变成了黑底, 无法输入文本.
点击 “初始化辅助” 后:

/bin/sh: D:Program: command not found
 [+] [!] 检测到多台设备，根据 ADB_HOST 参数将自动选择设备
自动选择设备失败，请根据上述内容自行输入数字并选择
>[1]    6503 terminated  python3 GUI_start.py

此时整个界面卡死.
```
还请你们做好cross-platform的debug工作... 也要照顾好广大macOS和Linux用户...

**Comment by RunningMelos** [comment]
应该是字体的锅，可以尝试安装 python 后在程序目录使用命令行文件
`python ArknightsShell.py -s -t slim:次数`
可以相对快捷地调用slim模式，当然更详细的指令可以参考[这里](https://github.com/ninthDevilHAUNSTER/ArknightsAutoHelper/blob/912f765de04710e93e482a85e40dc46afeda6ad7/Arknights/ArknightsShell.py#L39-L53)

**Comment by AndyChen2005121** [comment]
@RunningMelos ???
**我问的是GUI的问题,谢谢.**

**Comment by RunningMelos** [comment]
彳亍口巴。
最新版本暂时没有GUI，而作者忙着考研估计也没时间整，我只是给你一个替代性的建议（🤷‍♂️

Andy Chen <notifications@github.com> 于 2019年10月19日周六 下午11:10写道：
