### ISSUE TITLE
ValueError: invalid literal for int() with base 10: ''

### ISSUE THREAD

**Issue by LittleNightmare** [ninthDevilHAUNSTER/ArknightsAutoHelper#78]
```
2019-09-21 09:18:31,548 ! INFO ! base ! module_battle_slim ! 178 ! 检查关卡界面
Traceback (most recent call last):
  File "E:/GitHub/ArknightsAutoHelper/start.py", line 12, in <module>
    Ark.main_handler(clear_tasks=True, task_list=TASK_LIST)
  File "E:\GitHub\ArknightsAutoHelper\Arknights\base.py", line 422, in main_handler
    flag = self.module_battle(c_id, count)
  File "E:\GitHub\ArknightsAutoHelper\Arknights\base.py", line 403, in module_battle
    self_fix=self.ocr_active)
  File "E:\GitHub\ArknightsAutoHelper\Arknights\base.py", line 180, in module_battle_slim
    recoresult = imgreco.before_operation.recognize(screenshot)
  File "E:\GitHub\ArknightsAutoHelper\imgreco\before_operation.py", line 61, in recognize
    'consume': int(consumetext)
ValueError: invalid literal for int() with base 10: ''

Process finished with exit code 1
```
先写个issue等我学完物理和critical thinking再查

**Comment by dantmnf** [comment]
我的 fork 里已经修了
